/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/customers/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List locations */
        get: operations["listLocations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List workouts */
        get: operations["listWorkouts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workouts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a workout */
        get: operations["getWorkout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List classes (schedule)
         * @description Retrieve classes within a date range and optional filters to build a schedule.
         */
        get: operations["listClasses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/classes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a class */
        get: operations["getClass"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Location: {
            /** @example 9721 */
            id?: number;
            /** @example One Life CrossFit */
            name?: string;
            /** @example 2627 Skyway Drive */
            street_address_1?: string;
            /** @example Unit B */
            street_address_2?: string;
            /** @example Santa Maria */
            city?: string;
            /** @example 21 */
            state_id?: number;
            /** @example California */
            state?: string;
            /** @example 93455-1405 */
            zip_code?: string;
            /** @example 57 */
            country_id?: number;
            /** @example United States of America */
            country?: string;
            /** @example  */
            province?: string;
            /** @example onelifecrossfit.com */
            website?: string;
            /** @example 8057140338 */
            phone_number?: string;
            /**
             * Format: email
             * @example info@onelifecrossfit.com
             */
            email?: string;
            /** @example true */
            show_in_wodifind?: boolean;
            /** @example One Life CrossFit */
            wodifind_name?: string;
            wodifind_description?: string;
            email_signature?: string;
            /** @example true */
            enable_email_signature?: boolean;
            /** @example One Life CrossFit */
            email_from_label?: string;
            staff_signature?: string;
            abn_number?: string;
            gst_number?: string;
            /** @example 2 */
            business_type_id?: number;
            /** @example 9621 */
            customer_id?: number;
            /** @example  */
            stripe_terminal_location_id?: string;
            /** @example 62 */
            time_zone_id?: number;
            /** @example (GMT-08:00) Pacific Time - Los Angeles */
            time_zone?: string;
            /** @example America/Los_Angeles */
            time_zone_iana?: string;
            /** @example 2627 Skyway Drive<br/>Unit B<br/>Santa Maria, CA 93455-1405 */
            formatted_address?: string;
            /** @example 0 */
            lead_owner_id?: number;
            /** @example  */
            lead_owner?: string;
            /** @example 0 */
            client_owner_id?: number;
            /** @example  */
            client_owner?: string;
            created?: {
                /** @example 17597 */
                created_by_id?: number;
                /** @example System User */
                created_by?: string;
                /**
                 * Format: date-time
                 * @example 2022-03-10T12:51:51Z
                 */
                created_on_datetime?: string;
            } & {
                [key: string]: unknown;
            };
            updated?: {
                /** @example 17597 */
                updated_by_id?: number;
                /** @example System User */
                updated_by?: string;
                /**
                 * Format: date-time
                 * @example 2025-10-02T16:53:41Z
                 */
                updated_on_datetime?: string;
            } & {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        Workout: {
            /** @example wo_98765 */
            id?: string;
            /**
             * Format: date
             * @example 2025-11-05
             */
            date?: string;
            /** @example WOD: Cindy */
            title?: string;
            /** @example AMRAP 20: 5 pull-ups, 10 push-ups, 15 air squats */
            description?: string;
            /** @example prog_gpp */
            programId?: string;
            /** @example loc_12345 */
            locationId?: string;
            coachNotes?: string;
            publicNotes?: string;
        } & {
            [key: string]: unknown;
        };
        Class: {
            /** @example class_24680 */
            id?: string;
            /** @example CrossFit */
            name?: string;
            /**
             * Format: date-time
             * @example 2025-11-05T17:00:00-08:00
             */
            startTime?: string;
            /**
             * Format: date-time
             * @example 2025-11-05T18:00:00-08:00
             */
            endTime?: string;
            /** @example loc_12345 */
            locationId?: string;
            /** @example prog_gpp */
            programId?: string;
            coach?: {
                /** @example coach_001 */
                id?: string;
                /** @example Alex M */
                name?: string;
            } & {
                [key: string]: unknown;
            };
            /** @example 18 */
            capacity?: number;
            /** @example 12 */
            registeredCount?: number;
            /** @example 0 */
            waitlistCount?: number;
            /** @example scheduled */
            status?: string;
        } & {
            [key: string]: unknown;
        };
        Paged_Classes: {
            classes?: components["schemas"]["Class"][];
            pagination?: {
                /** @example 1 */
                page?: number;
                /** @example 100 */
                page_size?: number;
                /** @example true */
                has_more?: boolean;
            } & {
                [key: string]: unknown;
            };
            /** @example  */
            wodify_validation_result?: string;
        } & {
            [key: string]: unknown;
        };
        Paged_Locations: {
            locations?: components["schemas"]["Location"][];
            pagination?: {
                /** @example 1 */
                page?: number;
                /** @example 1 */
                page_size?: number;
                /** @example false */
                has_more?: boolean;
            } & {
                [key: string]: unknown;
            };
            /** @example  */
            wodify_validation_result?: string;
        } & {
            [key: string]: unknown;
        };
        Paged_Workouts: {
            data?: components["schemas"]["Workout"][];
            /** @example 50 */
            limit?: number;
            /** @example 0 */
            offset?: number;
            /** @example 31 */
            total?: number;
        } & {
            [key: string]: unknown;
        };
        Error: {
            /** @example invalid_request */
            error?: string;
            /** @example The provided token is expired. */
            message?: string;
            /** @example 401 */
            status?: number;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: {
        /** @description Filter by location id. */
        LocationId: string;
        /** @description Filter by program id. */
        ProgramId: string;
        /** @description Filter by coach id. */
        CoachId: string;
        /** @description Start date (YYYY-MM-DD). */
        StartDate: string;
        /** @description End date (YYYY-MM-DD). */
        EndDate: string;
        /** @description Page size. */
        Limit: number;
        /** @description Pagination offset. */
        Offset: number;
        /** @description Sort order: 'sort=snake_cased_attribute' or 'sort=desc_snake_cased_attribute'. Example: sort=desc_updated_on */
        Sort: string;
        /** @description Page number (1-based). */
        Page: number;
        /** @description Number of records per page (max 100). */
        PageSize: number;
        /** @description Resource identifier. */
        IdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listLocations: {
        parameters: {
            query?: {
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
                /** @description Pagination offset. */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A paged list of locations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paged_Locations"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listWorkouts: {
        parameters: {
            query?: {
                /** @description Start date (YYYY-MM-DD). */
                startDate?: components["parameters"]["StartDate"];
                /** @description End date (YYYY-MM-DD). */
                endDate?: components["parameters"]["EndDate"];
                /** @description Filter by location id. */
                locationId?: components["parameters"]["LocationId"];
                /** @description Filter by program id. */
                programId?: components["parameters"]["ProgramId"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
                /** @description Pagination offset. */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A paged list of workouts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paged_Workouts"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getWorkout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workout */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workout"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listClasses: {
        parameters: {
            query?: {
                /** @description Start date (YYYY-MM-DD). */
                startDate?: components["parameters"]["StartDate"];
                /** @description End date (YYYY-MM-DD). */
                endDate?: components["parameters"]["EndDate"];
                /** @description Filter by location id. */
                locationId?: components["parameters"]["LocationId"];
                /** @description Filter by program id. */
                programId?: components["parameters"]["ProgramId"];
                /** @description Filter by coach id. */
                coachId?: components["parameters"]["CoachId"];
                /** @description Sort order: 'sort=snake_cased_attribute' or 'sort=desc_snake_cased_attribute'. Example: sort=desc_updated_on */
                sort?: components["parameters"]["Sort"];
                /** @description Page number (1-based). */
                page?: components["parameters"]["Page"];
                /** @description Number of records per page (max 100). */
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A paged list of classes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paged_Classes"];
                };
            };
            /** @description Invalid filters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getClass: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier. */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Class */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Class"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
